### ISSUE TITLE
TODO - Basic wallet / dApp functionality

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/council-toolkit-app#3]
Why? lets get familiar with MeshSDK

- [x] Read UTxOs from wallet
- [x] Build transactions using wallet UTxOs
- [x] Sign transactions with wallet
- [x] Submit transactions with wallet
